name: Deploy Data Collector Service

on:
  push:
    branches:
      - main
    paths:
      - 'applications/data-collector/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Apply
        run: |
          cd applications/data-collector/terraform
          terraform init -backend-config="bucket=${{ vars.GCP_TF_STATE_BUCKET }}"
          terraform apply -auto-approve \
            -var="project_id=${{ vars.GCP_PROJECT_ID }}" \
            -var="region=${{ vars.GCP_REGION }}" \
            -var="app_name=${{ vars.COLLECTOR_SVC_NAME }}" \
            -var="db_instance_name=${{ vars.DB_INSTANCE_NAME }}" \
            -var="db_name=${{ vars.DB_NAME }}" \
            -var="db_user=${{ secrets.DB_USERNAME }}" \
            -var="db_pass=${{ secrets.DB_PASSWORD }}"

      - name: Build & Deploy Application
        id: deploy-cloud-run
        run: |
          gcloud builds submit --pack=image=gcr.io/${{ vars.GCP_PROJECT_ID }}/${{vars.COLLECTOR_SVC_NAME }},env=GOOGLE_RUNTIME_VERSION=21
          
          # Capture the generated URL from the deployment output
          RUN_URL=$(gcloud run deploy ${{vars.COLLECTOR_SVC_NAME }} \
            --image gcr.io/${{ vars.GCP_PROJECT_ID }}/${{vars.COLLECTOR_SVC_NAME }} \
            --region ${{ vars.GCP_REGION }} \
            --no-allow-unauthenticated \
            --add-cloudsql-instances=${{ vars.GCP_PROJECT_ID }}:${{ vars.GCP_REGION }}:${{ vars.DB_INSTANCE_NAME }} \
            --set-env-vars="SPRING_PROFILES_ACTIVE=gcp,DB_USERNAME=${{ secrets.DB_USERNAME }},DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
            --format='value(status.url)')
          
          echo "SERVICE_URL=$RUN_URL" >> $GITHUB_ENV

      - name: Update Scheduler Target URL
        run: |
          gcloud scheduler jobs update http mlb-daily-sync \
            --uri="${{ env.SERVICE_URL }}/fetch-games" \
            --location=${{ vars.GCP_REGION }}