spring:
  application:
    name: data-collector
  datasource:
    url: jdbc:postgresql://localhost:5432/mlb_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  cloud:
    gcp:
      sql:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

mlb:
  api:
    base-url: ${MLB_API_URL:https://statsapi.mlb.com/api}
